2024-10-02 17:38:26,301 - ERROR - Error connecting to Dog CEO API: HTTPSConnectionPool(host='dog.ceo', port=443): Max retries exceeded with url: /api/breed/poodle/images/random (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000257B01B01F0>: Failed to resolve 'dog.ceo' ([Errno 11001] getaddrinfo failed)"))
2024-10-02 18:00:51,063 - ERROR - Database error: 1049 (42000): Unknown database 'dog_api'
